Happ 539 notification icon and msg update
bcgov/myhealthBC-android pull request #122
Opened 2022-03-04 06:19 UTC by rashmi-bambhania

- Updated notification icon and message 
- Notification messages given by designer team is as follow:
Retrieving records.
Record updated.
Fail to retrive records.

2022-03-04 08:39 UTC, amit-metri requested changes

2022-03-04 08:39 UTC, amit-metri commented on common/src/main/res/values/strings.xml
> +    <string name="notification_title_on_success">Record updated.</string>
Could have been "Records updated."

2022-03-04 08:39 UTC, amit-metri commented on common/src/main/res/values/strings.xml
> +    <string name="notification_title_on_failed">Fail to retrieve records.</string>
Could have been "Failed to retrieve records."

2022-03-04 19:29 UTC, pinakinkansara approved these changes

2022-03-07 05:53 UTC, amit-metri approved these changes

2022-03-07 06:26 UTC, merged