Network call for lab report PDF
bcgov/myhealthBC-android pull request #126
Opened 2022-03-07 09:41 UTC by amit-metri

-added network call for fetching pdf data of lab report

2022-03-07 10:26 UTC, rashmi-bambhania commented on data/src/main/java/ca/bc/gov/data/datasource/remote/LaboratoryRemoteDataSource.kt
> +        if (isLabTestPdfResponseValid(response)) {
Add ! in if condition like below:
if (!isLabTestPdfResponseValid(response)) {
Because when response is invalid then we need to throw error.

2022-03-07 10:30 UTC, rashmi-bambhania requested changes
Requested one change

2022-03-07 11:42 UTC, rashmi-bambhania approved these changes

2022-03-08 05:17 UTC, pinakinkansara approved these changes

2022-03-08 08:30 UTC, merged