Show all comments + bugfix
bcgov/myhealthBC-android pull request #216
Opened 2022-04-20 07:30 UTC by amit-metri

-added show all comments screen
-bugfix on number of comments text display

2022-04-20 11:40 UTC, rashmi-bambhania requested changes

2022-04-20 11:40 UTC, rashmi-bambhania commented on app/src/main/java/ca/bc/gov/bchealth/ui/comment/CommentsViewModel.kt
> +                        Comment(it.id, it.text, it.createdDateTime)
Convert to current timezone if required

2022-04-20 11:40 UTC, rashmi-bambhania commented on app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsViewModel.kt
> +                val firsComment = comments.minByOrNull { it.createdDateTime }
We need to show latest comment.

2022-04-20 17:21 UTC, amit-metri commented on app/src/main/java/ca/bc/gov/bchealth/ui/healthrecord/medication/MedicationDetailsViewModel.kt
> +                val firsComment = comments.minByOrNull { it.createdDateTime }
Taken care of this.

2022-04-21 05:09 UTC, rashmi-bambhania approved these changes

2022-04-21 05:36 UTC, merged